CREATE OR REPLACE FUNCTION FNC_PERSONS_FEMALE() RETURNS 
TABLE(ID BIGINT, NAME VARCHAR, AGE INTEGER, GENDER 
VARCHAR, ADDRESS VARCHAR) AS $$ 
	 SELECT * FROM person WHERE gender = 'female' $$ LANGUAGE sql;


CREATE OR REPLACE FUNCTION FNC_PERSONS_MALE() RETURNS 
TABLE(ID BIGINT, NAME VARCHAR, AGE INTEGER, GENDER 
VARCHAR, ADDRESS VARCHAR) AS $$ 
	 SELECT * FROM person WHERE gender = 'male' $$ LANGUAGE sql;


SELECT * FROM fnc_persons_male();

SELECT * FROM fnc_persons_female();